In [ ]:
from functools import reduce
import os
import re
import time

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn import neural_network

In [12]:
root_dir = 'data'
data_dir = os.path.join(root_dir, 'ml-1m/')
data_dir_20ml = os.path.join(root_dir, 'ml-20m/')

In [18]:
movie_df = pd.read_csv(os.path.join(data_dir, 'movies.dat'),
                       sep = '::',
                       names = ['mid', 'm_name', 'm_genre'],
                       engine = 'python',
                       encoding = 'latin-1')

In [22]:
display(movie_df.head())

   mid                              m_name                       m_genre
0    1                    Toy Story (1995)   Animation|Children's|Comedy
1    2                      Jumanji (1995)  Adventure|Children's|Fantasy
2    3             Grumpier Old Men (1995)                Comedy|Romance
3    4            Waiting to Exhale (1995)                  Comedy|Drama
4    5  Father of the Bride Part II (1995)                        Comedy

In [23]:
mid = 10
display(movie_df[movie_df.mid == mid])

   mid            m_name                    m_genre
9   10  GoldenEye (1995)  Action|Adventure|Thriller

In [27]:
name = 'Machine'
movie_df[movie_df.m_name.str.contains(name)]

       mid               m_name        m_genre
1409  1433  Machine, The (1994)  Comedy|Horror

In [ ]:
rating_df = pd.read_csv(os.path.join(data_dir, 'ratings.dat'),
                        sep = '::',
                        names = ['uid', 'mid', 'rating', 'timestamp'],
                        parse_dates = ['timestamp'],
                        infer_datetime_format = True,
                        engine = 'python')

C:\Users\mustapha.bouhsen\AppData\Local\Temp\ipykernel_3680\275773715.py:1: FutureWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  rating_df = pd.read_csv(os.path.join(data_dir, 'ratings.dat'),
C:\Users\mustapha.bouhsen\AppData\Local\Temp\ipykernel_3680\275773715.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  rating_df = pd.read_csv(os.path.join(data_dir, 'ratings.dat'),

In [30]:
rating_df

          uid   mid  rating  timestamp
0           1  1193       5  978300760
1           1   661       3  978302109
2           1   914       3  978301968
3           1  3408       4  978300275
4           1  2355       5  978824291
...       ...   ...     ...        ...
1000204  6040  1091       1  956716541
1000205  6040  1094       5  956704887
1000206  6040   562       5  956704746
1000207  6040  1096       4  956715648
1000208  6040  1097       4  956715569

[1000209 rows x 4 columns]