In [3]:
from functools import reduce
import os
import re 
import time

import numpy as np
import pandas as pd


import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn import neural_network

In [9]:
DATA_DIR = 'data/ml-1m'
DATA_DIR_20ML = 'data/ml-20m' # for tags

In [11]:
movies_pd = pd.read_csv(os.path.join(DATA_DIR, 'movies.dat'),
                        sep='::',
                        names=['mid', 'mName', 'mGenders'],
                        engine='python', encoding='latin-1')


display(movies_pd.head())

   mid                               mName                      mGenders
0    1                    Toy Story (1995)   Animation|Children's|Comedy
1    2                      Jumanji (1995)  Adventure|Children's|Fantasy
2    3             Grumpier Old Men (1995)                Comedy|Romance
3    4            Waiting to Exhale (1995)                  Comedy|Drama
4    5  Father of the Bride Part II (1995)                        Comedy

In [17]:
mid = 10
display(movies_pd[movies_pd.mid == mid])

name = 'Machine'
display(movies_pd[movies_pd.mName.str.contains(name,
                                               regex=False, case=False)])

   mid             mName                   mGenders
9   10  GoldenEye (1995)  Action|Adventure|Thriller

       mid                mName       mGenders
1409  1433  Machine, The (1994)  Comedy|Horror

In [22]:
ratings_pd = pd.read_csv(os.path.join(DATA_DIR, 'ratings.dat'),
                         sep='::',
                         names=['uid', 'mid', 'rating', 'timestamp'],
                         parse_dates=['timestamp'],
                         infer_datetime_format=True,
                         engine='python')

TypeError: read_csv() got an unexpected keyword argument 'infer_datetime_format'